CREATE [ <table_type><table_name> | <replica_name> }
   <table_contents_source>
   [<system_versioning_spec>]
   [<application_time_period_configuration>]
   [<bi_temporal_table_spec>]
   [<with_association_clause>] 
   [<with_annotation_clause>]
   [<with_mask_clause>]        
   [<logging_option>] 
   [<auto_merge_option>]
   [<unload_priority_clause>]
   [<partition_clause>] 
   [<persistent_memory_spec_clause>] 
   [<group_option_list>]
   [<location_clause>] 
   [<replica_clause>]
   [<with_replica_list>] 
   [<global_temporary_option>] 
   [<unused_retention_period_option>] 
   [<record_commit_timestamp_clause>]            
   [<table_comment_string>]
   [<numa_node_preference_clause>]
   [<load_unit>]
   [<primary_key_update_clause>]