Create_Table_Statements ::=  Create_Table_Stmt | Create_Virtual_Table_Stmt

Create_Table_Stmt::= "CREATE" "table_type"? "TABLE" table_name 
    table_contents_source 
    "logging_option"? 
    "auto_merge_option"?
    "unload_priority_clause"? 
    "schema_flexibility_option"?
    "partition_clause"?
    "group_option"?
    "location_clause"?
    "replica_clause"?
    "global_temporary_option"?
    "series_clause"?

 Create_Virtual_Table_Stmt ::= "CREATE" "VIRTUAL" "TABLE" table_name 
    remote_location_clause